service: extrinsic-functions-demo

plugins:
  - serverless-plugin-extrinsic-functions

provider:
  name: aws
  runtime: nodejs8.10

custom:
  json: '{ "nested": { "field": 42 } }'

functions:
  hello:
    handler: handler.hello
    environment:
      STARTS_WITH_DEV:
        Fn::StartsWith: [ "${opt:stage}", dev ]  # use in functions
      MAX:
        Fn::Max: [ 40, 42 ] # should be 42
      MIN:
        Fn::Min: [ 40, 42 ] # should be 40
      NESTED_FIELD:
        Fn::JsonPath: [ "${self:custom.json}", "nested.field" ]
      NESTED_FIELD_SSM:
        Fn::JsonPath: [ "${ssm:/workshop-yancui/dev/serviceQuotas}", "searchMaxCount" ]

resources:
  Conditions:
    StartsWithDev:
      Fn::StartsWith: [ dev-yan, dev ]
    GreaterThan42:
      Fn::GreaterThan: [ 30, 42 ]

  Resources:
    AlarmTopic:
      Type: AWS::SNS::Topic
      Condition: GreaterThan42
      Properties:
        DisplayName: extrinsic-functions-topic
        TopicName: extrinsic-functions-topic
